### ISSUE TITLE
Issue with block_smb_web_client.php

### ISSUE THREAD

**Issue by richfreestone** [gthomas2/moodle-block_smb_web_client#1]
Hi

I've discovered an issue with the file block_smb_web_client.php

On line 100, it doesn't allow you to change the name of the share, only the name of the block or "My Home Directory" by changing [[homedir]]

Shouldn't this be changeable to suit the users preferences?

**Comment by gthomas2** [comment]
Thanks Rich. In the latest version I've modified this line to just use the language string for 'homedir'. Language strings can be customised in Moodle.
